version: '3.1'
# Before launching this, please run something like :
# echo "oay938BoBo" | docker secret create secretpass -
services:

  drupal:
    image: drupal:8.2
    ports:
      - 8000:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes

  postgres:
  
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD_FILE = /run/secrets/secretpass
    secrets:
      - secretpass
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:

secrets:
  secretpass:
    external: true